### ISSUE TITLE
Fix crash on label refresh

### ISSUE THREAD

**Issue by robertraaijmakers** [robertraaijmakers/com.trashchecker#2]
Hi! Unfortunately, the app crashed while I was doing the following: (...) This is the stack trace: /app.js:498 return trashCollectionToken.setValue(textLabel); ^ TypeError: trashCollectionToken.setValue is not a function at TrashcanReminder.onUpdateLabel (/app.js:498:32) at ontimeout (timers.js:476:15) at tryOnTimeout (timers.js:304:5) at Timer.listOnTimeout (timers.js:264:5)

**Comment by robertraaijmakers** [comment]
Fixt, didn't see this crash report for a long time now.
