### ISSUE TITLE
Error while setting label in version 2.6.0

### ISSUE THREAD

**Issue by robertraaijmakers** [robertraaijmakers/com.trashchecker#61]
A crash occurred for your app (version 2.6.0) at Sep 6, 2019 4:48 AM (UTC).

Homey software version: 2.5.2

Crash report:
    /app.js:517
			responseText = Homey.__('speech.output.trashtypesycollectedonx',
			             ^

ReferenceError: responseText is not defined
    at TrashcanReminder.onUpdateLabel (/app.js:517:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by robertraaijmakers** [comment]
Error happens when multiple types of trash is collected on the same day. Error is fixt in 2.6.1 which is submitted for review at Athom
